[settings]
#stop on page processing errors?
strict = true

#display progress
verbose = true

#display detailed debug output?
debug = false

#where input files (pages and assets) are stored
site_dir = "site"

#where the output goes
build_dir = "build"

#pages with other extensions are considered static assets
#and copied to build/unchanged
page_file_extensions = ["htm","html","md","rst","adoc"]

#files with these extensions are ignored
ignore_extensions = "draft"

#treat files as content to insert in the template
#unless they have an <html> element in them
generator_mode = true
complete_page_selector = "html"

#use templates/main.html for page template
default_template_file = "templates/main.html"

#this content will be inserted into the <main> element,
#after its last already existing child
default_content_selector = "main"
default_content_action = "append_child"

#set the document type to HTML5, unless the 
#page already has a doctype declaration
doctype = <!DOCTYPE html>
keep_doctype = true

#indent html tags for readability
pretty_print_html = true

#translate site/about.html to build/about/index.html
#if set to false, then site/about.html will become build/about.html
clean_urls = true

#look for plugin files in plugins/
plugin_discovery = true
plugin_dirs = ["plugins"]


