[settings]
#stop on page processing errors?
strict = true

#display progress
verbose = true

#display detailed debug output?
debug = false

#where input files (pages and assets) are stored
site_dir = "site"

#where the output goes
build_dir = "build"

#pages with other extensions are considered static assets
#and copied to build/unchanged
page_file_extensions = ["htm","html","md","rst","adoc"]
